services:
  farmer-backend:
    build:
      context: ./backend
    container_name: farmer-backend
    ports:
      - "8000:8000"
    depends_on:
      - farmer-mongo
      - farmer-redis
    env_file:
      - backend/.env
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
    restart: always

  farmer-worker:
    build:
      context: ./backend
    container_name: farmer-worker
    command: >
      sh -c "celery -A app.tasks.celery_app.celery_app worker --loglevel=info"
    depends_on:
      - farmer-mongo
      - farmer-redis
    env_file:
      - backend/.env
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
    restart: always
    healthcheck:
      test: ["CMD", "celery", "-A", "app.tasks.celery_app.celery_app", "inspect", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5


  farmer-redis:
    image: redis:7.0
    container_name: farmer-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  farmer-mongo:
    image: mongo:7.0
    container_name: farmer-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: Admin123
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo_data:
